# Generated by Django 5.1.1 on 2024-10-22 01:58

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoHorno',
            fields=[
                ('batch', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('variedad', models.CharField(max_length=40)),
                ('temp_sobre_grano', models.FloatField()),
                ('temp_bajo_tela', models.FloatField()),
                ('temp_ambiente', models.FloatField()),
                ('hr_sobre_tela', models.FloatField()),
                ('p_apertura_damper', models.FloatField()),
                ('presion_diferencial', models.FloatField()),
                ('gas_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gas_et_1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gas_et_2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gas_et_3', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gas_et_4', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gas_et_5', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gas_et_6', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tiempo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tiempo_barra_e1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tiempo_barra_e2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tiempo_barra_e3', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tiempo_barra_e4', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tiempo_barra_e5', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tiempo_barra_e6', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sp_temp_1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sp_temp_2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sp_temp_3', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sp_temp_4', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sp_temp_5', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sp_temp_6', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'INFO_HORNO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InfoProduccion',
            fields=[
                ('batch', models.IntegerField(primary_key=True, serialize=False)),
                ('id_tipo_malta', models.IntegerField()),
                ('id_tipo_horno', models.IntegerField()),
                ('fecha_horneo', models.DateField()),
                ('tipo_variedad', models.CharField(max_length=60)),
                ('cebada_limpia', models.FloatField()),
                ('cebada_sucia', models.FloatField()),
                ('falla', models.IntegerField()),
                ('impureza', models.IntegerField()),
                ('polvo', models.IntegerField()),
                ('malta_sucia', models.IntegerField()),
                ('brote', models.IntegerField()),
                ('pijilla_malta', models.IntegerField()),
                ('malta_limpia', models.IntegerField()),
                ('malta_verde', models.IntegerField()),
                ('materiaseca', models.IntegerField()),
                ('fecha_volteo', models.DateField()),
                ('fecha_pulido', models.DateField()),
                ('silo_destino_1', models.CharField(max_length=60)),
                ('kg_destino_1', models.IntegerField()),
                ('silo_destino_2', models.CharField(blank=True, max_length=60, null=True)),
                ('kg_destino_2', models.IntegerField(blank=True, null=True)),
                ('electricidad', models.IntegerField()),
                ('agua', models.IntegerField()),
                ('gas', models.IntegerField()),
                ('cs_ci', models.FloatField()),
                ('ci_mi', models.FloatField()),
                ('factor_perdida_humedad', models.FloatField()),
                ('factor_perdida_conversion', models.FloatField()),
                ('kg_perdida_humedad', models.IntegerField()),
                ('kg_perdida_conversion', models.IntegerField()),
                ('factor_carbon', models.FloatField()),
                ('factor_electricidad', models.FloatField()),
                ('factor_agua', models.FloatField()),
                ('info_horno_fecha', models.DateField()),
                ('info_tina_cod_tina', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Información de Producción',
                'verbose_name_plural': 'Información de Producción',
                'db_table': 'INFO_PRODUCCION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('role', models.CharField(max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
